name: Build
on:
  pull_request:
    types:
      - opened
      - edited
      - ready_for_review
      - reopened
      - synchronize
  push:
  workflow_dispatch:

jobs:
  build:
    if: contains(github.event.head_commit.message, '[skip ci]') == false

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Nasm install
      uses: ilammy/setup-nasm@v1
    - name: UPX install
      uses: "./github/actions/setup-upx"

    - name: build
      run: build.bat wc

    #- name: test
    #  run: test.bat wc

    #- name: make snapshot name
    #  id: snapshotname
    #  run: |
    #    (
    #      today=`date -u +%F | tr '\n' '-'`
    #      s_sha=`echo -n ${GITHUB_SHA} | cut -c1-8`
    #      printf "fname=snapshot-%s%s\n" $today $s_sha >> $GITHUB_OUTPUT
    #    )

    #- name: upload
    #  if: github.repository == 'FDOS/freecom' &&
    #    (github.event_name == 'push' || github.event.pull_request.merged == true)
    #  uses: actions/upload-artifact@v4
    #  with:
    #    name: ${{ steps.snapshotname.outputs.fname }}
    #    path: _output
